//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Olib.Local {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Local {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Local() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Olib.Local.Local", typeof(Local).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на F2 - start/stop auto-click.
        /// </summary>
        public static string AutoclickerControl {
            get {
                return ResourceManager.GetString("AutoclickerControl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Control:.
        /// </summary>
        public static string AutoclickerH {
            get {
                return ResourceManager.GetString("AutoclickerH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Auto-click time in milliseconds:.
        /// </summary>
        public static string AutoclickerTime {
            get {
                return ResourceManager.GetString("AutoclickerTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Attention! It is not recommended to bet less than 5!.
        /// </summary>
        public static string AutoclickerWarning {
            get {
                return ResourceManager.GetString("AutoclickerWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на About.
        /// </summary>
        public static string ButtonAbout {
            get {
                return ResourceManager.GetString("ButtonAbout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Enable effective autoclicker.
        /// </summary>
        public static string ButtonAutoclickerToolTip {
            get {
                return ResourceManager.GetString("ButtonAutoclickerToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Return to previous page.
        /// </summary>
        public static string ButtonBackToolTip {
            get {
                return ResourceManager.GetString("ButtonBackToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Close program.
        /// </summary>
        public static string ButtonCloseToolTip {
            get {
                return ResourceManager.GetString("ButtonCloseToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Converter.
        /// </summary>
        public static string ButtonConverter {
            get {
                return ResourceManager.GetString("ButtonConverter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Convert Values.
        /// </summary>
        public static string ButtonConverterToolTip {
            get {
                return ResourceManager.GetString("ButtonConverterToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Activate data parser.
        /// </summary>
        public static string ButtonDataParserToolTip {
            get {
                return ResourceManager.GetString("ButtonDataParserToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Global.
        /// </summary>
        public static string ButtonGlobal {
            get {
                return ResourceManager.GetString("ButtonGlobal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Go to Main page.
        /// </summary>
        public static string ButtonGlobalToolTip {
            get {
                return ResourceManager.GetString("ButtonGlobalToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Hide program.
        /// </summary>
        public static string ButtonMinimToolTip {
            get {
                return ResourceManager.GetString("ButtonMinimToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Roulette.
        /// </summary>
        public static string ButtonRoulette {
            get {
                return ResourceManager.GetString("ButtonRoulette", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Play roulette.
        /// </summary>
        public static string ButtonRouletteToolTip {
            get {
                return ResourceManager.GetString("ButtonRouletteToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Area.
        /// </summary>
        public static string ConverterArea {
            get {
                return ResourceManager.GetString("ConverterArea", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Binary.
        /// </summary>
        public static string ConverterBinary {
            get {
                return ResourceManager.GetString("ConverterBinary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Currency.
        /// </summary>
        public static string ConverterCurrency {
            get {
                return ResourceManager.GetString("ConverterCurrency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Data.
        /// </summary>
        public static string ConverterData {
            get {
                return ResourceManager.GetString("ConverterData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Decimal.
        /// </summary>
        public static string ConverterDecimal {
            get {
                return ResourceManager.GetString("ConverterDecimal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Length.
        /// </summary>
        public static string ConverterLength {
            get {
                return ResourceManager.GetString("ConverterLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Mass.
        /// </summary>
        public static string ConverterMass {
            get {
                return ResourceManager.GetString("ConverterMass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Pressure.
        /// </summary>
        public static string ConverterPressure {
            get {
                return ResourceManager.GetString("ConverterPressure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ruble.
        /// </summary>
        public static string ConverterRuble {
            get {
                return ResourceManager.GetString("ConverterRuble", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на https://www.cbr-xml-daily.ru/daily_eng_utf8.xml.
        /// </summary>
        public static string ConverterSource {
            get {
                return ResourceManager.GetString("ConverterSource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Temperature.
        /// </summary>
        public static string ConverterTemperature {
            get {
                return ResourceManager.GetString("ConverterTemperature", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Author: Dmitry Zhutkov.
        /// </summary>
        public static string InfoAuthor {
            get {
                return ResourceManager.GetString("InfoAuthor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Author: Dmitry Mirzoyan.
        /// </summary>
        public static string InfoAuthor2 {
            get {
                return ResourceManager.GetString("InfoAuthor2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Acknowledgments.
        /// </summary>
        public static string InfoButtonAcknowledgments {
            get {
                return ResourceManager.GetString("InfoButtonAcknowledgments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на View list of thanks.
        /// </summary>
        public static string InfoButtonAcknowledgmentsToolTip {
            get {
                return ResourceManager.GetString("InfoButtonAcknowledgmentsToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на To support.
        /// </summary>
        public static string InfoButtonToSupport {
            get {
                return ResourceManager.GetString("InfoButtonToSupport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Version September 17, 2019.
        /// </summary>
        public static string InfoDataVersion {
            get {
                return ResourceManager.GetString("InfoDataVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на The program was created to facilitate tasks and for fun..
        /// </summary>
        public static string InfoDescription {
            get {
                return ResourceManager.GetString("InfoDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Download complete, starting ....
        /// </summary>
        public static string InfoDownloadCompleted {
            get {
                return ResourceManager.GetString("InfoDownloadCompleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Download....
        /// </summary>
        public static string InfoDownloadingUpdate {
            get {
                return ResourceManager.GetString("InfoDownloadingUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Failed to download update..
        /// </summary>
        public static string InfoErrorDownload {
            get {
                return ResourceManager.GetString("InfoErrorDownload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Go to program repositories.
        /// </summary>
        public static string InfoGitHubToolTip {
            get {
                return ResourceManager.GetString("InfoGitHubToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на The latest version of the program is installed..
        /// </summary>
        public static string InfoLatestUpdate {
            get {
                return ResourceManager.GetString("InfoLatestUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Update Available v.
        /// </summary>
        public static string InfoNewUpdate {
            get {
                return ResourceManager.GetString("InfoNewUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на References:.
        /// </summary>
        public static string InfoReferences {
            get {
                return ResourceManager.GetString("InfoReferences", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Help the author in the further development of the program by depositing a certain amount.
        /// </summary>
        public static string InfoToSupportToolTip {
            get {
                return ResourceManager.GetString("InfoToSupportToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Go to the VK program group.
        /// </summary>
        public static string InfoVKToolTip {
            get {
                return ResourceManager.GetString("InfoVKToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Wait....
        /// </summary>
        public static string InfoWait {
            get {
                return ResourceManager.GetString("InfoWait", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на To use the application, click on the buttons below.
        /// </summary>
        public static string LabelContent1 {
            get {
                return ResourceManager.GetString("LabelContent1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Before you start using the program, you should know these things:
        ///1. The program will ALWAYS be launched only with administrator rights, this is to download the update without any complaints on the system drive, also with the auto-update program, to edit: the registry, where, in fact, is the directory of the installed program; remove the old version of the program and install a new one on the system drive, while nothing will happen to the system itself;
        ///2. The program - NOT VIRUS! This is just a false ant [остаток строки не уместился]&quot;;.
        /// </summary>
        public static string License {
            get {
                return ResourceManager.GetString("License", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Accept.
        /// </summary>
        public static string LicenseAccept {
            get {
                return ResourceManager.GetString("LicenseAccept", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на middle mouse button on the program close button..
        /// </summary>
        public static string LicenseChance1 {
            get {
                return ResourceManager.GetString("LicenseChance1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на right-click on the button to close the program..
        /// </summary>
        public static string LicenseChance2 {
            get {
                return ResourceManager.GetString("LicenseChance2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на middle-click on the Refuse button..
        /// </summary>
        public static string LicenseChance3 {
            get {
                return ResourceManager.GetString("LicenseChance3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на right-click on the Deny button..
        /// </summary>
        public static string LicenseChance4 {
            get {
                return ResourceManager.GetString("LicenseChance4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на middle-click on the Accept button..
        /// </summary>
        public static string LicenseChance5 {
            get {
                return ResourceManager.GetString("LicenseChance5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на right-click on the Accept button..
        /// </summary>
        public static string LicenseChance6 {
            get {
                return ResourceManager.GetString("LicenseChance6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на License agreement.
        /// </summary>
        public static string LicenseHeading {
            get {
                return ResourceManager.GetString("LicenseHeading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Message.
        /// </summary>
        public static string LicenseMessage {
            get {
                return ResourceManager.GetString("LicenseMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на You must read the license agreement first!.
        /// </summary>
        public static string LicenseMessage1 {
            get {
                return ResourceManager.GetString("LicenseMessage1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Not so fast! You should still read the license agreement..
        /// </summary>
        public static string LicenseMessage2 {
            get {
                return ResourceManager.GetString("LicenseMessage2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на I know that you want to run the program, but you still need to read the license agreement..
        /// </summary>
        public static string LicenseMessage3 {
            get {
                return ResourceManager.GetString("LicenseMessage3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на I get the point! You want to play the game &quot;How many times click Accept&quot; with me. Now your score:.
        /// </summary>
        public static string LicenseMessage4 {
            get {
                return ResourceManager.GetString("LicenseMessage4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Your score:.
        /// </summary>
        public static string LicenseMessage5 {
            get {
                return ResourceManager.GetString("LicenseMessage5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Refuse.
        /// </summary>
        public static string LicenseRefuse {
            get {
                return ResourceManager.GetString("LicenseRefuse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Discover.
        /// </summary>
        public static string ParseXMLButton1 {
            get {
                return ResourceManager.GetString("ParseXMLButton1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Clear the list.
        /// </summary>
        public static string ParseXMLButton2 {
            get {
                return ResourceManager.GetString("ParseXMLButton2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Save to file.
        /// </summary>
        public static string ParseXMLButton3 {
            get {
                return ResourceManager.GetString("ParseXMLButton3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на ID VKontakte:.
        /// </summary>
        public static string ParseXMLLabelComboBox1 {
            get {
                return ResourceManager.GetString("ParseXMLLabelComboBox1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на IP address:.
        /// </summary>
        public static string ParseXMLLabelComboBox2 {
            get {
                return ResourceManager.GetString("ParseXMLLabelComboBox2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Phone number:.
        /// </summary>
        public static string ParseXMLLabelComboBox3 {
            get {
                return ResourceManager.GetString("ParseXMLLabelComboBox3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Saved!.
        /// </summary>
        public static string ParseXMLListSave {
            get {
                return ResourceManager.GetString("ParseXMLListSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Fill out the list first.
        /// </summary>
        public static string ParseXMLNoList {
            get {
                return ResourceManager.GetString("ParseXMLNoList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на You cannot parse an empty field!.
        /// </summary>
        public static string ParseXMLNoParse {
            get {
                return ResourceManager.GetString("ParseXMLNoParse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Withdraw.
        /// </summary>
        public static string RandomButtonCheckName {
            get {
                return ResourceManager.GetString("RandomButtonCheckName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Display data below.
        /// </summary>
        public static string RandomButtonCheckNameToolTip {
            get {
                return ResourceManager.GetString("RandomButtonCheckNameToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Free mode.
        /// </summary>
        public static string RandomButtonFreeMode {
            get {
                return ResourceManager.GetString("RandomButtonFreeMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Create your own roulette.
        /// </summary>
        public static string RandomButtonFreeModeToolTip {
            get {
                return ResourceManager.GetString("RandomButtonFreeModeToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Twist.
        /// </summary>
        public static string RandomButtonTwist {
            get {
                return ResourceManager.GetString("RandomButtonTwist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Please, wait....
        /// </summary>
        public static string RandomButtonTwistExpectation {
            get {
                return ResourceManager.GetString("RandomButtonTwistExpectation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Falls out: .
        /// </summary>
        public static string RandomButtonTwistOut {
            get {
                return ResourceManager.GetString("RandomButtonTwistOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Try your luck.
        /// </summary>
        public static string RandomButtonTwistToolTip {
            get {
                return ResourceManager.GetString("RandomButtonTwistToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Zero out.
        /// </summary>
        public static string RandomButtonZeroOut {
            get {
                return ResourceManager.GetString("RandomButtonZeroOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Reset item lunge data.
        /// </summary>
        public static string RandomButtonZeroOutToolTip {
            get {
                return ResourceManager.GetString("RandomButtonZeroOutToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на We will twist for: You.
        /// </summary>
        public static string RandomStringName1 {
            get {
                return ResourceManager.GetString("RandomStringName1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на We will twist for: .
        /// </summary>
        public static string RandomStringName2 {
            get {
                return ResourceManager.GetString("RandomStringName2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Total drop options: .
        /// </summary>
        public static string RandomStringOptions {
            get {
                return ResourceManager.GetString("RandomStringOptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Enter first and last name here.
        /// </summary>
        public static string RandomTextBoxNameToolTip {
            get {
                return ResourceManager.GetString("RandomTextBoxNameToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Click &quot;Spin&quot; to try your luck.
        /// </summary>
        public static string RandomTextBoxRdmGlobal {
            get {
                return ResourceManager.GetString("RandomTextBoxRdmGlobal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Loose roulette.
        /// </summary>
        public static string RouletteFX {
            get {
                return ResourceManager.GetString("RouletteFX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Add item to list.
        /// </summary>
        public static string RouletteFXAddToolTip {
            get {
                return ResourceManager.GetString("RouletteFXAddToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Add.
        /// </summary>
        public static string RouletteFXButtonAdd {
            get {
                return ResourceManager.GetString("RouletteFXButtonAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Edit.
        /// </summary>
        public static string RouletteFXButtonEdit {
            get {
                return ResourceManager.GetString("RouletteFXButtonEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Delete input field after adding item.
        /// </summary>
        public static string RouletteFXCheckBox1 {
            get {
                return ResourceManager.GetString("RouletteFXCheckBox1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Erase all items after importing the XML / TXT file.
        /// </summary>
        public static string RouletteFXCheckBox2 {
            get {
                return ResourceManager.GetString("RouletteFXCheckBox2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Exclude duplicates when selecting items from a list.
        /// </summary>
        public static string RouletteFXCheckBox3 {
            get {
                return ResourceManager.GetString("RouletteFXCheckBox3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Copy.
        /// </summary>
        public static string RouletteFXCopy {
            get {
                return ResourceManager.GetString("RouletteFXCopy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Delete.
        /// </summary>
        public static string RouletteFXDelete {
            get {
                return ResourceManager.GetString("RouletteFXDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Edit.
        /// </summary>
        public static string RouletteFXEdit {
            get {
                return ResourceManager.GetString("RouletteFXEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Erase everything.
        /// </summary>
        public static string RouletteFXErase {
            get {
                return ResourceManager.GetString("RouletteFXErase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Remove all items from the list..
        /// </summary>
        public static string RouletteFXEraseToolTip {
            get {
                return ResourceManager.GetString("RouletteFXEraseToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Export.
        /// </summary>
        public static string RouletteFXExport {
            get {
                return ResourceManager.GetString("RouletteFXExport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Save list of elements to XML/TXT file.
        /// </summary>
        public static string RouletteFXExportToolTip {
            get {
                return ResourceManager.GetString("RouletteFXExportToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на File uploaded successfully!.
        /// </summary>
        public static string RouletteFXFileLoad {
            get {
                return ResourceManager.GetString("RouletteFXFileLoad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на File saved successfully! Way: .
        /// </summary>
        public static string RouletteFXFileSave {
            get {
                return ResourceManager.GetString("RouletteFXFileSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Import.
        /// </summary>
        public static string RouletteFXImport {
            get {
                return ResourceManager.GetString("RouletteFXImport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Load items from XML/TXT file to list.
        /// </summary>
        public static string RouletteFXImportToolTip {
            get {
                return ResourceManager.GetString("RouletteFXImportToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Items: .
        /// </summary>
        public static string RouletteFXItems {
            get {
                return ResourceManager.GetString("RouletteFXItems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на No name.
        /// </summary>
        public static string RouletteFXListName {
            get {
                return ResourceManager.GetString("RouletteFXListName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Normal mode.
        /// </summary>
        public static string RouletteFXNormalMode {
            get {
                return ResourceManager.GetString("RouletteFXNormalMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Go to normal roulette mode.
        /// </summary>
        public static string RouletteFXNormalModeToolTip {
            get {
                return ResourceManager.GetString("RouletteFXNormalModeToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на You cannot change the item to empty!.
        /// </summary>
        public static string RouletteFXNullItem {
            get {
                return ResourceManager.GetString("RouletteFXNullItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на You cannot add an empty element!.
        /// </summary>
        public static string RouletteFXNullItemAdd {
            get {
                return ResourceManager.GetString("RouletteFXNullItemAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Number of items to select:.
        /// </summary>
        public static string RouletteFXNumber {
            get {
                return ResourceManager.GetString("RouletteFXNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Close change panel.
        /// </summary>
        public static string RouletteFXRenameCloseToolTip {
            get {
                return ResourceManager.GetString("RouletteFXRenameCloseToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Edit item.
        /// </summary>
        public static string RouletteFXRenameToolTip {
            get {
                return ResourceManager.GetString("RouletteFXRenameToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Selections in seconds:.
        /// </summary>
        public static string RouletteFXSelections {
            get {
                return ResourceManager.GetString("RouletteFXSelections", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Settings.
        /// </summary>
        public static string RouletteFXSettings {
            get {
                return ResourceManager.GetString("RouletteFXSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Close settings panel.
        /// </summary>
        public static string RouletteFXSettingsCToolTip {
            get {
                return ResourceManager.GetString("RouletteFXSettingsCToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Open Settings Panel.
        /// </summary>
        public static string RouletteFXSettingsToolTip {
            get {
                return ResourceManager.GetString("RouletteFXSettingsToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Enter the item name here.
        /// </summary>
        public static string RouletteFXTextBoxNameToolTip {
            get {
                return ResourceManager.GetString("RouletteFXTextBoxNameToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Enter here the name of the item you want to change.
        /// </summary>
        public static string RouletteFXTextBoxRToolTip {
            get {
                return ResourceManager.GetString("RouletteFXTextBoxRToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Enter your text here..
        /// </summary>
        public static string RouletteFXTextChanToolTip {
            get {
                return ResourceManager.GetString("RouletteFXTextChanToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Click Twist.
        /// </summary>
        public static string RouletteFXTwist {
            get {
                return ResourceManager.GetString("RouletteFXTwist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Select an item from the list..
        /// </summary>
        public static string RouletteFXTwistToolTip {
            get {
                return ResourceManager.GetString("RouletteFXTwistToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Reset dropout data from an item from the list.
        /// </summary>
        public static string RouletteFXZeroOutToolTip {
            get {
                return ResourceManager.GetString("RouletteFXZeroOutToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Exception: .
        /// </summary>
        public static string StringException {
            get {
                return ResourceManager.GetString("StringException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Program information.
        /// </summary>
        public static string ToolTipAbout {
            get {
                return ResourceManager.GetString("ToolTipAbout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Welcome.
        /// </summary>
        public static string Welcome {
            get {
                return ResourceManager.GetString("Welcome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Close a window.
        /// </summary>
        public static string WindowClose {
            get {
                return ResourceManager.GetString("WindowClose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Maximize a window.
        /// </summary>
        public static string WindowMaximized {
            get {
                return ResourceManager.GetString("WindowMaximized", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Minimize a window.
        /// </summary>
        public static string WindowRollup {
            get {
                return ResourceManager.GetString("WindowRollup", resourceCulture);
            }
        }
    }
}
